extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [ zipkin ]
      processors: [ batch ]
      exporters: [ logging, otlp ]
  extensions: [ memory_ballast, zpages ]
